### ISSUE TITLE
Filtering entries throws error

### ISSUE THREAD

**Issue by bigardone** [liuchengxu/vim-clap#619]
**Environment (please complete the following information):**
 - OS: macOS Big Sur
 - (Neo)Vim version: NVIM v0.5.0-602e750
 - vim-clap version: Release v0.22
 - Have you reproduced with a minimal vimrc: Not yet
 - Have you updated to the latest plugin version: Yes
 - Have you upgraded to/compiled the latest Rust binary: Yes 

**Describe the bug**
Whenever I run `:Clap files`, `:Clap buffers`, or any other commando which lets me filter the results, it throws an error every time I press a key:

```
vim-clap: Vim(return):Error invoking 'python_eval' on channel 4 (python3-script-host):^@error caught in request handler 'python_eval ['clap_fzy_rs()']':^@Traceback (most recent call last):^@  File "
/Users/user/Library/Python/3.7/lib/python/site-packages/pynvim/plugin/script_host.py", line 169, in python_eval^@    return eval(expr, self.module.__dict__)^@  File "<string>", line 1,
in <module>^@  File "/Users/user/.nvim/plugged/vim-clap/pythonx/clap/fzy.py", line 65, in clap_fzy_rs^@    vim.eval("a:match_type"), vim.eval("a:bonus"))^@TypeError: fuzzy_match() takes
 at most 5 positional arguments (6 given), throwpoint:function clap#handler#on_typed[24]..42[6]..clap#impl#on_typed[9]..<SNR>142_on_typed_sync_impl[20]..clap#filter#on_typed[1]..clap#filter#sync[2].
.clap#filter#sync#python#[5]..provider#python3#Call, line 18
Press ENTER or type command to continue
```

**Clap debug**

```
            has cargo: 1
            has maple: /Users/user/.nvim/plugged/vim-clap/target/release/maple
           maple info: version 0.1.22, built for x86_64-apple-darwin by rustc 1.49.0 (e1884a8e3 2020-12-29).
         has +python3: 1
has py dynamic module: 1
            has ctags: ctags without JSON output support
    Current sync impl: Python
     Current FileType:
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/Users/user/.nvim/plugged/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = 0
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_fuzzy_match_hl_groups = [0]
    let g:clap_insert_mode_only = 1
    let g:clap_layout = {'width': '72%', 'relative': 'editor'}
    let g:clap_match_color = ['#5E81AC', '12']
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
    let g:clap_provider_grep_executable = 'rg'
    let g:clap_provider_grep_opts = '--glob !.git/ --hidden --no-heading --smart-case --vimgrep'
Press ENTER or type command to continue
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type `:Clap files`

4. Press any key to filter the list of files

**Expected behavior**
It should filter the results without any error.

**Screenshots**

![image](https://user-images.githubusercontent.com/1090272/105167531-20f26a80-5b19-11eb-9dfe-63916686dc89.png)

**Comment by liuchengxu** [comment]
Recompile the Python dynamic module, `bonus` is added in https://github.com/liuchengxu/vim-clap/pull/614.
