### ISSUE TITLE
maple panic when call :Clap grep

### ISSUE THREAD

**Issue by zoumi** [liuchengxu/vim-clap#899]
```vim
:Clap grep ++opt=--no-ignore ++opt=--no-cache ++query=is_git_repo
```

debug output:
```
grep.init
clap#job#regular#forerunner#start_command
run_maple_command: maple --winwidth 129 --case-matching smart ripgrep-forerunner --cmd-dir D:\programs\vim\vimfiles\plugged\vim-clap --output-threshold 100000
start_bffered:42
vim-clap: thread 'main' panicked at 'Argument 'grep-query' is a positional argument and can't have short or long name versions', D:\programs\registry\src\xxx\clap-3.2.22\src\builder\debug_asserts.rs:679:9
stack backtrace:
vim-clap:    0: std::panicking::begin_panic_handler
             at /rustc/29e4a9ee0253cd39e552a77f51f11f9a5f1c41e6/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/29e4a9ee0253cd39e552a77f51f11f9a5f1c41e6/library\core\src\panicking.rs:142
   2: clap::builder::debug_asserts::assert_arg
             at D:\programs\registry\src\xxx\clap-3.2.22\src\builder\debug_asserts.rs:679
   3: clap::builder::debug_asserts::assert_app
             at D:\programs\registry\src\xxx\clap-3.2.22\src\builder\debug_asserts.rs:70
   4: clap::builder::command::App::_build_self
             at D:\programs\registry\src\xxx\clap-3.2.22\src\builder\command.rs:4340
   5: clap::builder::command::App::_build_subcommand
             at D:\programs\registry\src\xxx\clap-3.2.22\src\builder\command.rs:4425
   6: clap::parser::parser::Parser::parse_subcommand
             at D:\programs\registry\src\xxx\clap-3.2.22\src\parser\parser.rs:676
   7: clap::parser::parser::Parser::get_matches_with
             at D:\programs\registry\src\xxx\clap-3.2.22\src\parser\parser.rs:469
   8: clap::builder::command::App::_do_parse
             at D:\programs\registry\src\xxx\clap-3.2.22\src\builder\command.rs:4204
   9: clap::builder::command::App::try_get_matches_from_mut<ref_mut$<std::env::ArgsOs>,std::ffi::os_str::OsString>
             at D:\programs\registry\src\xxx\clap-3.2.22\src\builder\command.rs:730
  10: clap::builder::command::App::get_matches_from<ref_mut$<std::env::ArgsOs>,std::ffi::os_str::OsString>
             at D:\programs\registry\src\xxx\clap-3.2.22\src\builder\command.rs:600
  11: clap::builder::command::App::get_matches
             at D:\programs\registry\src\xxx\clap-3.2.22\src\builder\command.rs:512
  12: clap::derive::Parser::parse<maple::Maple>
             at D:\programs\registry\src\xxx\clap-3.2.22\src\derive.rs:81
  13: maple::main::async_block$0
             at .\src\main.rs:43
  14: core::future::from_generator::impl$1::poll<enum$<maple::main::async_block_env$0> >
             at /rustc/29e4a9ee0253cd39e552a77f51f11f9a5f1c41e6\library\core\src\future\mod.rs:91
  15: tokio::park::thread::impl$5::block_on::closure$0<core::future::from_generator::GenFuture<enum$<maple::main::async_block_env$0> > >
             at D:\programs\registry\src\xxx\tokio-1.21.0\src\park\thread.rs:267
  16: tokio::coop::with_budget::closure$0<enum$<core::task::poll::Poll<enum$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<std::error::Error>,alloc::alloc::Global> >, 1, 18446744073709551615, Err> > >,tokio::park::thread::impl$5::block_on::closure_env$0<
             at D:\programs\registry\src\xxx\tokio-1.21.0\src\coop.rs:102
  17: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::try_with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum$<core::task::poll::Poll<enum$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<std::error
             at /rustc/29e4a9ee0253cd39e552a77f51f11f9a5f1c41e6\library\std\src\thread\local.rs:445
  18: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum$<core::task::poll::Poll<enum$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<std::error::Er
             at /rustc/29e4a9ee0253cd39e552a77f51f11f9a5f1c41e6\library\std\src\thread\local.rs:421
  19: tokio::coop::with_budget
             at D:\programs\registry\src\xxx\tokio-1.21.0\src\coop.rs:95
  20: tokio::coop::budget
             at 
vim-clap: D:\programs\registry\src\xxx\tokio-1.21.0\src\coop.rs:72
  21: tokio::park::thread::CachedParkThread::block_on<core::future::from_generator::GenFuture<enum$<maple::main::async_block_env$0> > >
             at D:\programs\registry\src\xxx\tokio-1.21.0\src\park\thread.rs:267
  22: tokio::runtime::enter::Enter::block_on<core::future::from_generator::GenFuture<enum$<maple::main::async_block_env$0> > >
             at D:\programs\registry\src\xxx\tokio-1.21.0\src\runtime\enter.rs:152
  23: tokio::runtime::scheduler::multi_thread::MultiThread::block_on<core::future::from_generator::GenFuture<enum$<maple::main::async_block_env$0> > >
             at D:\programs\registry\src\xxx\tokio-1.21.0\src\runtime\scheduler\multi_thread\mod.rs:79
  24: tokio::runtime::Runtime::block_on<core::future::from_generator::GenFuture<enum$<maple::main::async_block_env$0> > >
             at D:\programs\registry\src\xxx\tokio-1.21.0\src\runtime\mod.rs:492
  25: maple::main
             at .\src\main.rs:76
  26: core::ops::function::FnOnce::call_once<enum$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<std::error::Error>,alloc::alloc::Global> >, 1, 18446744073709551615, Err> (*)(),tuple$<> >
             at /rustc/29e4a9ee0253cd39e552a77f51f11f9a5f1c41e6\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
job finished:{'status': 'dead', 'cmd': ['maple', '--winwidth', '129', '--case-matching', 'smart', 'ripgrep-forerunner', '--cmd-dir', 'D:\programs\vim\vimfiles\plugged\vim-clap', '--output-threshold', '100000'], 'stoponexit': 'term', 'tty_out': '', 'exitval': 0, 'exit_cb': '', 'tty_in': '', 'channel': 'channel 42 buffered', 'tty_type': '', 'process': 844}
```

**Comment by liuchengxu** [comment]
Can not reproduce on ubuntu, please fill in the issue template completely.

**Comment by zoumi** [comment]
It's solved by updating rg.exe and maple.exe to the newest version.
